# Generated by Django 5.2.4 on 2025-08-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_active',
        ),
        migrations.AddField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry_date',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
    ]
