# Generated by Django 5.2.4 on 2025-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_promocode_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
